### ISSUE TITLE
accessing $keycloak within Router

### ISSUE THREAD

**Issue by djeverson** [dsb-norge/vue-keycloak-js#10]
Hello, 

I am struggling with getting access to $keycloak in the Router.  Any suggestions or examples on how to accomplish this?

Thanks, I appreciate any advice!

**Comment by djeverson** [comment]
Figured it out: router.app.$keycloak

Sorry for the noise.

**Comment by MohabAbugabal** [comment]
hi @djeverson . Appreciate your support. It is not working for me in vue3. Can you give me any tip, please? Grazie. 

**Main.js**
const myApp = createApp(App)
myApp.config.globalProperties.$keycloak = Keycloak;


const keycloak = Keycloak(initOptions)


myApp.use(ElementPlus)
myApp.use(VueAxios, axios)
myApp.use(store)
myApp.use(router)
myApp.config.globalProperties.$keycloak = keycloak;
myApp.mount("#app");

**router**
const preventRoutes = {
  beforeEnter: (to, from, next) => {

    if(store.state.loggedIn == true){
        next();
    }else {
       **next(router.myApp.$keycloak.login());**
    }

  }
