### ISSUE TITLE
Using $keycloak.token in vue 3?

### ISSUE THREAD

**Issue by adityar15** [dsb-norge/vue-keycloak-js#105]
I want to use keycloak token in Vue 3 ts in the function below

```
function tokenInterceptor () {
    axios.interceptors.request.use(config => {
      config.headers.Authorization = `Bearer ${Vue.prototype.$keycloak.token}`
      return config
    }, error => {
      return Promise.reject(error)
    })
  }
```

How can I do it?

Also, will it solve the problem of token refresh and login redirection on every page refresh?

**Comment by baltom** [comment]
Vue 3 does not use prototype. Should find it on app.config.globalProperties.$keycloak.token where "app" is your vue instance.

**Comment by baltom** [comment]
Closing this issue with the answer above. Please note however issue #96

**Comment by idc77** [comment]
How do you access app from a vue 3 sfc then?
