### ISSUE TITLE
accessing $keycloak values results in all of them being null.

### ISSUE THREAD

**Issue by acebelowzero** [dsb-norge/vue-keycloak-js#109]
using vue 3 javascript not type script.
![keycloak glitch](https://user-images.githubusercontent.com/64754588/131942167-1c5369f5-bfde-4db3-b86c-5a5fdacc2475.PNG)

but just printing the result from `app.config.globalProperties.$keycloak ` has all the values I need.
![keycloak](https://user-images.githubusercontent.com/64754588/131942747-b337c2a1-f1d5-4af1-9fb9-57bb528a848e.PNG)

**Comment by baltom** [comment]
This is the same underlying issue as mentioned already in https://github.com/dsb-norge/vue-keycloak-js/issues/96 and https://github.com/dsb-norge/vue-keycloak-js/issues/97
