### ISSUE TITLE
"Client secret not provided in request"

### ISSUE THREAD

**Issue by bdparrish** [dsb-norge/vue-keycloak-js#11]
How do I provide a client secret in the config object?

error: "unauthorized_client"
error_description: "Client secret not provided in request"

**Comment by anderius** [comment]
You can't! :-)

You need to make the client public in Keycloak.

You can read more [here](https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter):

`One important thing to note about using client-side applications is that the client has to be a public client as there is no secure way to store client credentials in a client-side application. This makes it very important to make sure the redirect URIs you have configured for the client are correct and as specific as possible.`

**Comment by anderius** [comment]
There seems to be some undocumentet code in the keycloak javascript adapter, that supports a credentials object with a secret... Are you using this?

If we simply pass on the config object, as proposed in https://github.com/dsb-norge/vue-keycloak-js/issues/8, this would be possible.

I still can't see the use case for a secret in the javascript adapter. Can you perhaps explain how the secret would be used in your case?

**Comment by bdparrish** [comment]
This would be in reference to the confidential access type.  Take a look at [keycloak-angular](https://github.com/mauriciovigolo/keycloak-angular).  They have implemented using the client secret in order to complete the confidential workflow.

**Comment by anderius** [comment]
I still don't see how the secret would be a secret if it is sent to the browser...

But the code is (undocumented) in the Keycloak javascript adapter.

I am in favor of solving this by passing the config object directly to Keycloak, as suggested in https://github.com/dsb-norge/vue-keycloak-js/issues/8.

Hopefully we will have this fixed by tomorrow, one way or the other!
