### ISSUE TITLE
VueKeyCloak ignores config

### ISSUE THREAD

**Issue by jonathan-longe** [dsb-norge/vue-keycloak-js#110]
VueKeyCloak appears to ignore the config.  Can someone point out what I'm doing wrong?

Create new app using:  `$ vue create keycloak-test`

Install VueKeyCloak using:  `$ npm install @dsb-norge/vue-keycloak-js --save`

Modify "main.js" as follows:

```
import Vue from 'vue'
import App from './App.vue'
import VueKeyCloak from '@dsb-norge/vue-keycloak-js'

Vue.use(VueKeyCloak)

Vue.use(VueKeyCloak, {
  config:'https://my.keycloak.server/auth',
  onReady: kc => {
    console.log('keycloak returns',kc)
    new Vue({
      render: h => h(App)
    }).$mount('#app')
  }
})
```

Run: `$ npm run serve`

Using Chrome, navigate to:  http://localhost:8080/
The "Console" tab of the Chrome Developer tools shows a call to:
GET http://localhost:8080/config 404 (Not Found)

I was expecting a call to:
GET https://my.keycloak.server/auth (not the actual server name)

I also tried replacing the config with an object instead of a string:
```
config: {
    realm: 'MyRealm',
    url: 'https://my.keycloak.server/auth',
    clientId: 'MyClientId'
}
```

But the config object also appears to have no effect. The browser still shows a call to the default "http://localhost:8080/config".

Here's the dependencies section from the "package.json" file:
```
  "dependencies": {
    "@dsb-norge/vue-keycloak-js": "*",
    "core-js": "^3.6.5",
    "vue": "^2.6.11"
  },
```

Any suggestions?

**Comment by baltom** [comment]
You have one additional `Vue.use(VueKeyCloak)` before you again configure another instance of it. So im guessing that it's responsible for the request to /config ?

**Comment by jonathan-longe** [comment]
Duh!  I don't know why I didn't notice that! Thanks @baltom!
