### ISSUE TITLE
Unable to redirect custom sign-up page

### ISSUE THREAD

**Issue by Logeswaranbca** [dsb-norge/vue-keycloak-js#111]
When i try to navigate my custom sign-up page its not redirect that page,

**Comment by baltom** [comment]
Not quite sure i understand what you are trying to accomplish. Do you have any code examples?

**Comment by Logeswaranbca** [comment]
I would like to navigate the page Sign up page

1) When user hit the url Keycloak login page displayed and i have added one button in keycloack login page --> Sign up button
2) But User click the Sign up button it will not redirect Custom Sign-up page, It will redirect same Keycloak login page

import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";

import VueKeycloakJs from "@dsb-norge/vue-keycloak-js";
import { KeycloakInstance } from "keycloak-js";
import { VueKeycloakInstance } from "@dsb-norge/vue-keycloak-js/dist/types";

const app = createApp(App);
app.use(VueKeycloakJs, {
  config: {
    url: "https://keycloak.xxxx.com:xxxx/auth/",
    realm: "xxxx-xx",
    clientId: "xxxxxxx",
  },
  init: {
    onLoad: "login-required",
    checkLoginIframe: false,
  },
  onReady(keycloak: KeycloakInstance) {
    app.mount("#app");
  },
});
app.use(store);
app.use(router);


declare module "@vue/runtime-core" {
  interface ComponentCustomProperties {
    $keycloak: VueKeycloakInstance;
  }
}

**Comment by baltom** [comment]
Sounds to me like you are outside the control of this plugin. You have specified in your configuration `login-required`, which will force your user to go to your configured keycloak url to authenticate (As in outside the Vue app). And when authenticated the user would get sent back to your app with the necessary information in the $keycloak object. 

In your keycloak realm settings, under the "Login" tab you should be able to enable "User registration", which will add the correct button to your login page.

**Comment by Logeswaranbca** [comment]
Yes its navigate Keycloak User registration page but i need to navigate my custom signup page

**Comment by baltom** [comment]
And your custom signup page is in your keycloak instance? Or in your vue application?

**Comment by Logeswaranbca** [comment]
My Vue application

**Comment by baltom** [comment]
To be able to use you vue application without being authenticated you would need to use `check-sso` instead of `login-required`, Should probably read https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter as mentioned in the README. That should allow you to use your sign up page in your vue application.
