### ISSUE TITLE
error when 'check-sso' is set on live build

### ISSUE THREAD

**Issue by idc77** [dsb-norge/vue-keycloak-js#114]
I'm using this package with quasar v2, which means vue v3.
library version is latest v2.1.0-beta

You can see the error live at https://6s4.de/
username: keycloak-tester
password: tester-123456

When I set login-required this error doesn't happen. But I want the content to be public, so 'check-sso' it is.
I have to reload the page in order to be logged in.
This doesn't happen in dev environment.

It could be a keycloak configuration mistake on my side.
![6s4-keycloak-config](https://user-images.githubusercontent.com/87644834/139399797-36c047f4-0733-4201-890a-e80a280af14f.png)

the console log, which doesn't say much
```
vendor.c5f870c1.js:6 Error: Could not initialized keycloak-js adapter
    at vendor.c5f870c1.js:6 {error: 'login_required', error_description: undefined}error: "login_required"error_description: undefined[[Prototype]]: Object
(anonymous) @ vendor.c5f870c1.js:6
Promise.catch (async)
a @ vendor.c5f870c1.js:6
(anonymous) @ vendor.c5f870c1.js:6
Promise.then (async)
(anonymous) @ vendor.c5f870c1.js:6
Promise.then (async)
install @ vendor.c5f870c1.js:6
use @ vendor.c5f870c1.js:6
(anonymous) @ app.79da4b37.js:1
(anonymous) @ app.79da4b37.js:1
O @ app.79da4b37.js:1
async function (async)
O @ app.79da4b37.js:1
(anonymous) @ app.79da4b37.js:1
Promise.then (async)
(anonymous) @ app.79da4b37.js:1
Promise.then (async)
2318 @ app.79da4b37.js:1
r @ app.79da4b37.js:1
(anonymous) @ app.79da4b37.js:1
r.O @ app.79da4b37.js:1
(anonymous) @ app.79da4b37.js:1
(anonymous) @ app.79da4b37.js:1
```
is essentially this webpack-bundled library. 

The boot file
```js
import { boot } from 'quasar/wrappers'
import VueKeyCloak from '@dsb-norge/vue-keycloak-js'
import axios from 'axios'

export default boot(async ({ app, router, store }) => {
  async function tokenInterceptor () {
    axios.interceptors.request.use(config => {
      config.headers.Authorization = `Bearer ${app.config.globalProperties.$keycloak.token}`
      return config
    }, error => {
      return Promise.reject(error)
    })
  }

  return new Promise(resolve => {
    app.use(VueKeyCloak, {
      init: {
        onLoad: 'check-sso',
        flow: 'standard',
        pkceMethod: 'S256',
        silentCheckSsoRedirectUri: window.location.origin + '/silent-check-sso.html',
        checkLoginIframe: false,
        scope: 'openid email profile roles',
      },
      config: {
        url: process.env.KEYCLOAK_URL,
        realm: process.env.KEYCLOAK_REALM,
        clientId: process.env.KEYCLOAK_CLIENTID

      },
      onReady: () => {
        tokenInterceptor()
        resolve()
      }
    })
  })
})
```

FWIW silent-check-sso.html
```
<html>
<body>
<script>
  parent.postMessage(location.href, location.origin)
</script>
</body>
</html>
```

**Comment by baltom** [comment]
My guess is your experiencing the same as mentioned here https://github.com/dsb-norge/vue-keycloak-js/issues/96 ? as stated on https://github.com/dsb-norge/vue-keycloak-js/releases/tag/v2.0.0-beta 

Although kind of wierd that you are getting a console error. It's usually just silent.

**Comment by idc77** [comment]
Hi baltom,

as far as I can understand issue 96 is different, as they get a blank page after reload. Here I get no output because the client apparently isn't logged in into keycloak but it logged in after a page refresh.
Idk if we are still able to use the non-beta version with Vue3. I didn't dive into Vue deep enough to be considered an expert.

My observation is as follows:

- I navigate to `https://6s4.de` on a new blank browser session
- routing redirects me from `/` to `/posts`
- optional: I open `https://6s4.de/posts` directly
- `https://6s4.de/posts#error=login_required&state=<some_uuid>`  is now in the browser's address field

So despite `onLoad: 'check-sso'`, who actually in detail?, expects the client to be logged in.

- I log in via the IDP's login page and get redirected back to `https://6s4.de/posts`
- error gets logged to console
```
Error: Could not initialized keycloak-js adapter
    at vendor.416da34b.js:6
onInitError @ app.378fc079.js:1
```

```js
onInitError:e=>{console.error(e)}
```
Sounds like some "watch" or state or timing problem with Vue3.

**Comment by idc77** [comment]
#116 fixes this issue on chromium, but not on firefox.

**Comment by cdecinkoKnight** [comment]
Has #116 been merged with the latest version? We are seeing this issue with v.2.2.0
