### ISSUE TITLE
Compilation error on 2.1.0-beta

### ISSUE THREAD

**Issue by gogo199432** [dsb-norge/vue-keycloak-js#115]
Hey, I'm getting the following issue with the newest version:
`Module '"vue"' has no exported member 'App'. Did you mean to use 'import App from "vue"' instead?`

I'm using:

-  Vue2 version 2.6.12
- Typescript 4.4.4

Let me know if you need the whole packages.json file

**Comment by baltom** [comment]
How are you loading the plugin and starting your app?

This sounds like an issue, as this plugin doesn't attempt to import App from vue

**Comment by gogo199432** [comment]
The error comes from your types.d.ts file on line two, or at least that's where VSCode complained:
`import type { App } from 'vue';`

I load the plugin like in the docs. In my main.ts:
```
Vue.use(VueKeyCloak, {
  config:{
    url: 'https://example.com/auth',
    realm: 'myrealm',
    clientId: 'clientid',
  },
  init:{
    onLoad: 'check-sso',
    silentCheckSsoRedirectUri: window.location.origin + "/silent-check-sso.html"
  },
  onReady: _=>{
    new Vue({
      router,
      vuetify,
      store,
      i18n,
      render: h => h(App)
    }).$mount('#app')}
})
```

**Comment by baltom** [comment]
Can you test this with the latest release 2.1.1-beta

**Comment by gogo199432** [comment]
Looks like the fix worked. I'll close the issue for now.
