### ISSUE TITLE
keycloak + vue3 + vite, keycloak not ready

### ISSUE THREAD

**Issue by rainbowechoes** [dsb-norge/vue-keycloak-js#117]
Hi, I want to use keycloak in vue3 + vite project.

So I do the same operation in example `vue3 ts`, but it report keycloak not ready. Here is my operations: 

1. use vite template:
`npm init vite@latest my-vue-app --template vue-ts`

2. add vue-keycloak-js 
`npm install @dsb-norge/vue-keycloak-js --save`

3. edit main.ts
```
import { createApp } from 'vue'
import App from './App.vue'

// keycloak 所需依赖
import VueKeyCloak from '@dsb-norge/vue-keycloak-js'
import {KeycloakInstance} from "keycloak-js";
import {VueKeycloakInstance} from "@dsb-norge/vue-keycloak-js/dist/types"


createApp(App).use(VueKeyCloak, {
    init: {
        onLoad: 'check-sso',
    },
    config: {
        url: 'http://localhost:8180/auth',
        realm: 'cloud-cmp',
        clientId: 'vue',
    },
    onReady(keycloak: KeycloakInstance) {
        console.log('Keycloak ready', keycloak)
    },
}).mount('#app')

// 全局声明 keycloak 变量
declare module '@vue/runtime-core' {
    interface ComponentCustomProperties {
        $keycloak: VueKeycloakInstance
    }
}

```

4. add html content in Hellowork.vue
```
  <div>
    <div v-if="$keycloak && $keycloak.ready">
      <div v-if="$keycloak.authenticated">
        <el-button type="warning" @click="$keycloak.logoutFn">Logout</el-button>
      </div>
      <div v-else>
        <el-button type="primary" @click="$keycloak.login">Login</el-button>
      </div>
    </div>
    <div v-else>
      keycloak not ready
    </div>
  </div>
```

this is my vite.config:
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
  server: {
    port: 3003,
    strictPort: true,
  }
})

```

keycloak is healthy, and keycloak config is work in vue2. But when I visited http://localhost:3003, it show this:
![image](https://user-images.githubusercontent.com/38370475/141231041-ecd236b0-a6d2-4c3f-bde2-e82638ea1b38.png)

why keycloak is not ready? I hope to get some help.

**Comment by baltom** [comment]
Can you test this with the latest release 2.1.1-beta

**Comment by idc77** [comment]
@rainbowechoes You also need the silent-check-sso.html file, especially when using 'check-sso'.

**Comment by rainbowechoes** [comment]
> Can you test this with the latest release 2.1.1-beta

thanks! I do as your example, it work well.

**Comment by rainbowechoes** [comment]
> @rainbowechoes You also need the silent-check-sso.html file, especially when using 'check-sso'.

thanks for your reply! But What is this page used for?

**Comment by baltom** [comment]
> > @rainbowechoes You also need the silent-check-sso.html file, especially when using 'check-sso'.
> 
> thanks for your reply! But What is this page used for?

It tells you about it here https://www.keycloak.org/docs/latest/securing_apps/#_javascript_adapter just search for "silentCheck" and you'll find it

**Comment by rainbowechoes** [comment]
> > > @rainbowechoes You also need the silent-check-sso.html file, especially when using 'check-sso'.
> > 
> > 
> > thanks for your reply! But What is this page used for?
> 
> It tells you about it here https://www.keycloak.org/docs/latest/securing_apps/#_javascript_adapter just search for "silentCheck" and you'll find it
Oh, I understand it! thanks for you help!!
