### ISSUE TITLE
Ensure README.md is published to npm

### ISSUE THREAD

**Issue by ajmas** [dsb-norge/vue-keycloak-js#122]
Currently the ReadMe is not published to npm: https://www.npmjs.com/package/@dsb-norge/vue-keycloak-js , it would be good to make sure it is.

**Comment by baltom** [comment]
Not quite sure i understand what you mean? The readme is there?
![Screenshot 2021-12-14 at 06 52 56](https://user-images.githubusercontent.com/10920353/145941046-ec80dd7f-0057-413a-aba6-2cbdac3ae11c.png)

**Comment by ajmas** [comment]
It is there now. Maybe npm misbehaving?
