### ISSUE TITLE
Question: Calling keycloak protected REST API in same realm? 

### ISSUE THREAD

**Issue by ajmas** [dsb-norge/vue-keycloak-js#123]
Having a hard time finding an answer to this question anywhere in the Keycloak community and hoping someone here can provide some light:

I am needing to allow the Vue application, using this package, to communicate with a API server that is also protected using Keycloak in the same realm. The client for the vue app is set to use public access-type, while the API server client configuration is set to use bearer access-type.

Server side is using keycloak-connect.

Client side I am using this in the axios interceptor (vue3):

```ts
      const keycloak = app.config.globalProperties.$keycloak;
   
      if (keycloak.authenticated) {
        const keycloak = app.config.globalProperties.$keycloak;
        const token = keycloak.token as string;
        if (token && config.headers) {
          config.headers.Authorization = `Bearer ${token}`;
        }
      }
```

What I see happening is:

 - call made to the endpoint of API server, with bearer token
 - server responds with 302, redirecting to */protocol/openid-connect/auth path of the keycloak server, with client_id used the API server
 - cors failure

**Comment by baltom** [comment]
Given that you want to authenticate inside your Vue application, the backend does not need it's own client. It seems to me that you have configured your backend to attempt to do the authentication. And not verifying the access token coming in. 

You would have to configure the jwk-uri in your backend:
https://KEYCLOAK_HOST/auth/realms/REALM/protocol/openid-connect/certs
There the backend will get the information it needs (certificates) to verify the signature of the JWTs coming from your Vue application. Thereby allowing you to use the API. Meaning if you went straight for your API server without a client you would get 401 or something. And not be sent to a login-screen

**Comment by ajmas** [comment]
Thanks, that's the best information I have had so far on this subject. I'll try this out and come back for more questions if I get stuck.
