### ISSUE TITLE
Could not initialized keycloak-js adapter

### ISSUE THREAD

**Issue by idc77** [dsb-norge/vue-keycloak-js#124]
My OCD is driving me crazy every time I see the typo.
Could not initialized... I'm not a native English speaker and this is not proper English.

The real issue though is, this with `adapter: 'cordova-native'` and the absolute absence of any meaningful error messages paired with the mutant English "could not initialized"

Can you at least fix the typo?

I'm guessing no one has ever successfully use this lib with  `adapter: 'cordova-native', am I wrong?

**Comment by baltom** [comment]
Fixed typo in https://github.com/dsb-norge/vue-keycloak-js/releases/tag/v2.1.3-beta and when mentioned exception/error is happening we are attempting to "bubble up" the exception which the keycloak-js adapter is giving us when attempting to initialize it   https://github.com/keycloak/keycloak/blob/main/adapters/oidc/js/src/main/js/keycloak.js#L60 so your error is coming from keycloak-js adapter. And no have not attempted to use this library with cordova-native before
