### ISSUE TITLE
how to stop onAuthSuccess setInterval

### ISSUE THREAD

**Issue by yaooooooooo** [dsb-norge/vue-keycloak-js#127]
current code: 
        const updateTokenInterval = setInterval(() => keycloak.updateToken(60).catch(() => {
            keycloak.clearToken();
        }), 10000);
        
plan1:
        options.onAuthSuccess? options.onAuthSuccess() : (const updateTokenInterval = setInterval(() =>  
                keycloak.updateToken(60).catch(() => {
                 keycloak.clearToken();
        }), 10000));
        
plan2:
        var updateTokenInterval = setInterval(() => keycloak.updateToken(60).catch(() => {
            keycloak.clearToken();
        }), 10000);
        
        i can clearInterval(window.updateTokenInterval);
        
 THX

**Comment by yaooooooooo** [comment]
> 

so i see, but i want to take session timeout sence and how to use watcher/inerval,

now my solution is when project initail i will clear All interval, 
because keycloak-js ---> "kc.onAuthSuccess && kc.onAuthSuccess();"

THK

**Comment by yaooooooooo** [comment]
> 

so i see, but i want to take session timeout scene and how to use watcher/inerval,

now my solution is when project initail i will clear All interval, 
because keycloak-js ---> "kc.onAuthSuccess && kc.onAuthSuccess();"

THX

**Comment by baltom** [comment]
I dont quite understand your question im afraid

**Comment by yaooooooooo** [comment]
Thank you very much. We have a plan to achieve session timeout.
