### ISSUE TITLE
token not refresh

### ISSUE THREAD

**Issue by Pettidjo** [dsb-norge/vue-keycloak-js#13]
i'm trying to understand why my token is not refreshed.

i have configured SSO Session max to : 2 minute

in my console : 

After 1 min, every ten second : 
dsb-vue-keycloak.umd.js:464 [KEYCLOAK] Refreshing token: token expired
dsb-vue-keycloak.umd.js:491 [KEYCLOAK] Token refreshed
dsb-vue-keycloak.umd.js:840 [KEYCLOAK] Estimated time difference between browser and server is 0 seconds

At 2 min : 
dsb-vue-keycloak.umd.js:516 POST http:*******
dsb-vue-keycloak.umd.js:501 [KEYCLOAK] Failed to refresh token
dsb-vue-keycloak.umd.js:1650 Error while trying to refresh the token

**Comment by anderius** [comment]
Is that not the desired behaviour?

From the Keycloak tooltip on "SSO session max" (which is default 10 hours):

`Max time before a session is expired. Tokens and browser sessions are invalidated when a session is expired."`

From my understanding, the refresh token is also invalidated.

**Comment by Pettidjo** [comment]
you are right, my bad!

i needed to change 'Access Token Lifespan', sorry for my misunderstanding.
