### ISSUE TITLE
Incorrect build for v2.1.4-beta

### ISSUE THREAD

**Issue by vdyakov** [dsb-norge/vue-keycloak-js#144]
Hi, I noticed that when installing v2.1.4-beta, there is a script in the dist folder that does not correspond to the main branch.

Links for comparison:
- [index.ts from v2.1.4-beta branch](https://github.com/dsb-norge/vue-keycloak-js/blob/v2.1.4-beta/src/index.ts)
- [link on file from dist](https://unpkg.com/browse/@dsb-norge/vue-keycloak-js@2.1.4-beta/dist/dsb-vue-keycloak.umd.js)

**Comment by baltom** [comment]
Thank you for pointing it out to us. I've released a new version which should contain the correct output https://github.com/dsb-norge/vue-keycloak-js/releases/tag/v2.1.5-beta
