### ISSUE TITLE
Constant refreshing when logged in and using offline_access token

### ISSUE THREAD

**Issue by antonio-petrov** [dsb-norge/vue-keycloak-js#147]
Hello,
I am using the example typescript_vue3 application and I am trying to use offline_token. The login works, the offline token also seems to be working (I can see in the admin console that there is an offline token in use now). The problem is on the line `vueKeycloak.login(KeycloakLoginOptions)` - it causes endless reloading of the page.

I read somewhere that the version of keycloak-js must be updated for it to work properly, I tried versions 9, 10, 15, 18 - none of them seem to be working.

The problem is reproduceable in the example application with the following changes:

```

createApp(App)
  .use(VueKeycloakJs, {
    init: {
      onLoad: 'login-required',
        silentCheckSsoRedirectUri: window.location.origin + "/silent-check-sso.html",
        checkLoginIframe: false
    },
    config: {
      url: '<actual_url_here>',
      clientId: '<client_id>',
      realm: 'master'
    },
    onReady (keycloak: KeycloakInstance, vueKeycloak: VueKeycloakInstance) {
      const KeycloakLoginOptions : KeycloakLoginOptions = {
        scope: "offline_access"
      };
      if (vueKeycloak != null && vueKeycloak.login != null){
        vueKeycloak.login(KeycloakLoginOptions) // the problem occurs on this line
      }
    }
  })
```

**Comment by baltom** [comment]
I would think you also need to change "login-required" to "check-sso". As with "login-required" the plugin will redirect you to login, and then your sent back to your app and "onReady" is called. Which is sending you back to login page and repeat

**Comment by antonio-petrov** [comment]
> I would think you also need to change "login-required" to "check-sso". As with "login-required" the plugin will redirect you to login, and then your sent back to your app and "onReady" is called. Which is sending you back to login page and repeat

Changing it did not help. In some other places I have seen people suggest removing the `silentCheckSsoRedirectUri` - that did not solve the problem either, unfortunately.

**Comment by JonasSchubert** [comment]
Setting the init-parameter `checkLoginIframe` to `false` solved the constant reload for me. This was described [here](https://github.com/mauriciovigolo/keycloak-angular/issues/222).

**Comment by antonio-petrov** [comment]
I do have that parameter set to `false`, but the line `vueKeycloak.login(KeycloakLoginOptions)` is the one causing the endless loop, not the `onReady` callback.

**Comment by antonio-petrov** [comment]
I have finally solved the problem. The way that I was trying to set up offline token is not correct.

This line was causing the issue:
`vueKeycloak.login(KeycloakLoginOptions) // the problem occurs on this line`

I believe that the line is directing the user to the login page, but the login page sees that the user is already logged in, so he is redirected back, etc, etc, resulting in endless loop.

**### Solution:**
Define `scope: "offline_access"` in the `init` itself, e.g.:
```

...
.use(VueKeycloakJs, {
    init: {
      onLoad: 'login-required',
        silentCheckSsoRedirectUri: window.location.origin + "/silent-check-sso.html",
        checkLoginIframe: false,
        scope: "offline_access"
    },
....
```
