### ISSUE TITLE
URL fragments are not being removed upon successful login

### ISSUE THREAD

**Issue by cdecinkoKnight** [dsb-norge/vue-keycloak-js#150]
With my Vue 2 sample, this does not occur. However with Vue 3 and the 2.1.5-beta we are seeing the fragments left behind on the URL, in the user's address bar. This feels like valuable information is being leaked, or at least made more visible. It can also be confusing to the user and will create broken URLs if they bookmark or share the page link.

**Comment by cdecinkoKnight** [comment]
According to the RFC, that's a no no and not in compliance:  https://www.rfc-editor.org/rfc/rfc6749#section-3.1.2

**Comment by baltom** [comment]
This is something which happens from time to time I've noticed. Both in vue 2 and 3. And its not something this plugin is controlling. Its the underlying keycloak-js plugin
