### ISSUE TITLE
$keycloak with vue 3 and vue-router 4

### ISSUE THREAD

**Issue by djdemarco** [dsb-norge/vue-keycloak-js#152]
In this example code in [router.js](https://github.com/dsb-norge/vue-keycloak-js/blob/main/examples/hello-keycloak/src/router.js)

```
const router = new Router({
  mode: 'history',
  base: process.env.BASE_URL,
  routes: [
    {
      path: '/',
      name: 'home',
      component: Home
    },
    {
      path: '/secret',
      name: 'secret',
      component: () => import(/* webpackChunkName: "secret" */ './views/Secret.vue'),
      meta: {
        requiresAuth: true
      }
    }
  ]
})

...

router.beforeEach(async (to, from, next) => {
  if (to.matched.some(record => record.meta.requiresAuth)) {
    // We wait for Keycloak init, then we can call all methods safely
    while (router.app.$keycloak.createLoginUrl === null) {
      await sleep(100)
    }
    if (router.app.$keycloak.authenticated) {
      next()
    } else {
      const loginUrl = router.app.$keycloak.createLoginUrl()
      window.location.replace(loginUrl)
    }
  } else {
    next()
  }
})
```

**$keycloak** is accessible via **router.app.$keycloak** when using vue-router 3.  However, this example won't work with vue 3 and vue-router 4.  How can I access $keycloak then?

**Comment by Karkisushant** [comment]
@djdemarco  Did you found any solutions to this issue ?

**Comment by MarcelCode** [comment]
It would be really great if someone can give an example how to use it with the router in vue3

**Comment by djdemarco** [comment]
> @djdemarco Did you found any solutions to this issue ?

I moved on to using another library since we will be using Nuxt 3 for the framework.  Also, in the future we might switch to another authentication provider other than Keycloak so it's best to use a library that can cater to a wide range of identity providers.  I'm using this now instead: https://github.com/sidebase/nuxt-auth

Nuxt 3's support of its native auth module is still in the planning stages as stated here: https://github.com/sidebase/nuxt-auth.  Hence the need to use another library for authentication.

**Comment by djdemarco** [comment]
I moved on to using another authentication library instead
