### ISSUE TITLE
Implementing PKCE with vue-keycloak-js

### ISSUE THREAD

**Issue by ingesa-mel** [dsb-norge/vue-keycloak-js#162]
This is a question and not an issue.

The Web Authorization Protocol workgroup of the Internet Engineering Task Force recommends for web apps to authenticate with Authorization Code flow and PKCE.

I was wondering if PKCE is supported by vue-keycloak-js and how it could be implemented.

If its not supported it would be nice to know what the reasoning is to not implement it.

**Comment by idc77** [comment]
Short and answer: It's the default.
```js
      app.use(VueKeyCloak, {
        init: {
          onLoad: 'login-required',
          flow: 'standard',
          pkceMethod: 'S256',
          silentCheckSsoRedirectUri: window.location.origin + '/silent-check-sso.html',
          checkLoginIframe: false,
          scope: 'openid email profile roles',
        },
// ...
}
```

**Comment by ingesa-mel** [comment]
thanks!
