### ISSUE TITLE
Not working with Keycloak 5.0.0?

### ISSUE THREAD

**Issue by jakobeissler** [dsb-norge/vue-keycloak-js#17]
Hi there.

I've upgraded my keycloak server from version 4.5.0 to 5.0.0 and now users are being logged out after a few seconds after logging in. No output in console, no errors.

Could this be a compatibility problem with KC 5.0.0?

Thanks.

**Comment by jakobeissler** [comment]
The problem isn't related to vue-keycloak. Somehow the KC coocki is lost after authentication.

**Comment by jakobeissler** [comment]
Downgraded to 4.8.3 and everything is working. Must be a bug in 5.0.0

**Comment by nlien** [comment]
Thanks for letting us know! We will pay close attention to this when we're testing the 5.0 version.
