### ISSUE TITLE
Document the use of client secret

### ISSUE THREAD

**Issue by anderius** [dsb-norge/vue-keycloak-js#22]
After receiving some questions around the use of client secret, I have create the following issue requesting a clarification:

https://issues.jboss.org/browse/KEYCLOAK-10276

Hopefully, we get some explanation we can include or point to from our doc.

**Comment by nlien** [comment]
@anderius What's your take on this issue? I noticed that the issue you posted above is closed, though no further explanation has arrived in the official Keycloak Javascript adapter docs. Should we close this issue as well?

**Comment by anderius** [comment]
The client secret is now removed from the javascript adapter (Keycloak 8):

https://www.keycloak.org/docs/latest/release_notes/index.html#credentials-support-removed-from-the-javascript-adapter
