### ISSUE TITLE
Redirect URI configuration

### ISSUE THREAD

**Issue by denniseffing** [dsb-norge/vue-keycloak-js#24]
Hi,

the Keycloak JS Adapter reference describes the method `login(options)` where the object `options` includes setting a redirect URI.

As far as I can see, vue-keycloak-js does not expose the `options` object of the login method. Therefore, the Keycloak Javascript Adapter always uses the current URI as redirect URI.

Because a user might refresh the page on any URI, the redirect URI of the client must be configured using a wildcard (i.e. `example.com/*`). 
Is there any way around this? I want to configure my redirect URI as strict as possible.

**Comment by nlien** [comment]
It should suffice to pass the options object to the function:
`$keycloak.login({ redirectUri: 'https://myserver.com' })`
See also #6 
Let me know if this doesn't work.

**Comment by nlien** [comment]
You can also pass a `redirectUri` to the logout function:
[https://github.com/dsb-norge/vue-keycloak-js#specify-a-redirecturi](https://github.com/dsb-norge/vue-keycloak-js#specify-a-redirecturi)

**Comment by denniseffing** [comment]
@nlien It only works when the user visits (for example) `example.com/resource/1` for the first time.

However, if the user is already logged in (e.g. Cookies are set) and visits or refreshes the page, this does not work.
I implemented the login like this:

Plugin initialization:
```javascript
Vue.use(VueKeycloak, {
  init: {
    onLoad: "check-sso"
  },
  // ... realm settings etc. 
});
```

Route guards
```javascript
router.beforeEach((to, from, next) => {
  if (to.matched.some(record => record.meta.requiresAuth)) {
    if (router.app.$keycloak.authenticated) {
      next(); // this doesn't work when the user refreshes the page
    } else {
      router.app.$keycloak.login({redirectUri: 'http://localhost:8171/'});
    }
  } else {
    next();
  }
});
```

**Comment by denniseffing** [comment]
I figured it out by looking at the Keycloak Javascript Adapter code. 
It turns out that the `init` method of the Keycloak object has a `redirectUri` parameter that can be set. This is not documented in the Keycloak Javascript Adapter reference.

Solution:
```javascript
Vue.use(VueKeycloak, {
  init: {
    onLoad: "check-sso",
    redirectUri: process.env.BASE_URL
  },
  // ... realm settings etc. 
});
```

**Comment by nlien** [comment]
Ah, you're right. Totally undocumented as you said. Fortunately we just pass the options object through, so this will work. I'm a little hesitant to document this feature on our side, since it's left out of the official docs. But, anyway, glad you figured it out!
