### ISSUE TITLE
Error handling when the Keycloak service is unavailable.

### ISSUE THREAD

**Issue by TimothySealy** [dsb-norge/vue-keycloak-js#25]
When using this plugin a Vue instance is mounted after the plugin has been initialised (and the onReady is called). When the Keycloak server is unavailable the onReady is never called and thus the Vue instance not mounted. The result is a black page when starting the frontend application. Is there a way to catch this error situation (maybe with an onError)? 

The official plugin (keycloak-js-bower) does not seem to have a function for this but maybe there is a way to catch this error situation. The only feedback I have now is the following message which is logged in the browsers console:
```
Failed to load resource: the server responded with a status of 503 (Service Unavailable).
```

**Comment by nlien** [comment]
I'm not sure there's much we can do in this case. The plugin merely calls Keycloak's init function, which in turn will redirect the user to the Keycloak's login page (or fail silently if using the 'check-sso' option). I'm not sure it's a good idea to expand the functionality of this plugin to check the availability of the Keycloak server.
