### ISSUE TITLE
How to detect when the token has expired

### ISSUE THREAD

**Issue by chongma** [dsb-norge/vue-keycloak-js#31]
If i leave my PC for a long time or overnight then sometimes the page may still be loaded but the token is expired.  it would be nice to be able to check for this and redirect to the login page.  i am using check-sso

**Comment by nlien** [comment]
Unfortunately, with the `check-sso` option, the plugin doesn't handle any specific action when the token is unsuccessfully refreshed. Behind the scenes, the plugin will call the KC's `clearToken` method when the token is not successfully refreshed, and when using `login-required` the `login` method is called, thus redirecting the user to the login page. In any case the `clearToken` method will call KC's `onAuthLogout`callback.

To handle this scenario we would have to add another callback (either `onAuthLogout` or `onAuthRefreshError`, or both) to the plugin, similarly to the `onReady` callback. Then you should be able to take appropriate action whenever these events happen.

I'd like to add this feature, but I'm not sure when it'll fit my schedule. I'll keep the issue open for now. In the meantime, you (or anyone else, for that matter) are welcome to submit a PR.

**Comment by wirk** [comment]
I have added the onAuthRefreshError callback as suggested.

**Comment by wirk** [comment]
@nlien would it be possible to merge my PR? Let me know if there is anything that needs improving etc.

**Comment by nlien** [comment]
I'll try to have a look at it, and merge it, in the next week or two. Thank you for the patience :-)

**Comment by nlien** [comment]
I'm sorry for the delay... Currently we're quite busy, so this will have to wait a little while yet.

**Comment by akademy** [comment]
Would love to see this...

**Comment by nlien** [comment]
Truly sorry for the delay. And while time has passed, I have switched job. As a result I can no longer administrate and update this repo. The fate of this plugin is therefore resting in the hands of the employees at https://github.com/dsb-norge (@anderius amongst others..)

Anyway, I'm sure someone there will take a look at this as soon as their schedule allows it...

P.S. The PR that is submitted should be ok to merge, as far as I can see.

**Comment by wirk** [comment]
thanks for the heads-up. Good luck with your new job. 

BTW, we ended up just copying the modified version into our project a few months ago and it's been working flawlessly. It's only a single file so not much of a hassle apart from being cut out from any future updates ;-)

We also recently updated the keycloak-js adapter `"keycloak-js": "^10.0.2"` and replaced the two occurrences of `keycloak.updateToken(60).error(...)` with `keycloak.updateToken(60).catch(...)` to use the native promise api.

**Comment by nlien** [comment]
Nice! That info is surely helpful when this plugin is updating the keycloak-js adapter dependency (which is about time 😅 ). Thanks again.

**Comment by thisisme** [comment]
I would like to see this also

**Comment by chongma** [comment]
Due to the keycloak-js being out of date I migrated to just using keycloak-js in my project and it works fine.  Here is a code sample if anyone else wants to do it:
(main.js)
```javascript
import Keycloak from 'keycloak-js'
import VueLogger from 'vuejs-logger';
const isProduction = process.env.NODE_ENV === 'production';
const options = {
  isEnabled: true,
  logLevel: isProduction ? 'error' : 'debug',
  stringifyArguments: false,
  showLogLevel: true,
  showMethodName: true,
  separator: '|',
  showConsoleColors: true
};
Vue.use(VueLogger, options);
const keycloakPath = `/${process.env.VUE_APP_KC_PATH}`;
var keycloak = new Keycloak(keycloakPath);
Vue.prototype.$keycloak = keycloak
keycloak.init({ onLoad: 'check-sso' }).then(() => {
  setInterval(async () => {
    try {
      const refreshed = await keycloak.updateToken(180)
      if (refreshed) {
        Vue.$log.debug('Token refreshed' + refreshed);
      } else {
        Vue.$log.warn('Token not refreshed, valid for '
          + Math.round(keycloak.tokenParsed.exp + keycloak.timeSkew - new Date().getTime() / 1000) + ' seconds');
      }
    } catch (err) {
      Vue.$log.error('Failed to refresh token');
      router.go();
    }
  }, 60000)
  new Vue({
    router,
    render: h => h(App)
  }).$mount('#app')
}).catch(function () {
  Vue.$log.error("Authenticated Failed");
});
```
You don't have to include any of the logging.  process.env.VUE_APP_KC_PATH is the path of the keycloak.json which needs to be put in public folder.  Then when i use axios i can get the token.
(api.js)
```javascript
import axios from 'axios';
import Vue from 'vue'
const instance = axios.create({
    baseURL: process.env.VUE_APP_BASE_URL
})
instance.interceptors.request.use((config) => {
    const token = Vue.prototype.$keycloak.token;
    if (token) {
        config.headers.Authorization = `Bearer ${token}`
    }
    return config
}, (err) => {
    return Promise.reject(err)
})
```
Because keycloak has been added to the prototype i can check authentication like this `$keycloak.authenticated` and logout like this `$keycloak.logout` and check realm role like this `$keycloak.hasRealmRole('somerole')`

There is also an onTokenExpired function.  I haven't had time to check if it works properly but it could work something like this
(main.js)
```javascript
keycloak.onTokenExpired = () => {
  console.log('token expired', keycloak.token);
  keycloak.updateToken(30).then((refreshed) => {
    if (refreshed) {
      Vue.$log.debug('Token refreshed' + refreshed);
    } else {
      Vue.$log.warn('Token not refreshed, valid for '
        + Math.round(keycloak.tokenParsed.exp + keycloak.timeSkew - new Date().getTime() / 1000) + ' seconds');
    }
  }).catch(() => {
    Vue.$log.error('Failed to refresh token');
    router.go();
  });
}
```

**Comment by christophernruud** [comment]
Almost a year in the making, I have merged the PR into the codebase. Will look into whether handling onAuthSuccess is necessary as well. 
The callback is lacking documentation, though, might need to add that

**Comment by christophernruud** [comment]
Closing this issue as resolved.
