### ISSUE TITLE
Javascript plugin token not compatible with Java plugin token

### ISSUE THREAD

**Issue by chongma** [dsb-norge/vue-keycloak-js#32]
this may be an issue for the keycloak team but they are usually pretty busy. if i login first using the javascript plugin and then navigate to a java endpoint secured by the java keycloak plugin (tomcat) then it gives me an infinite redirect error.  however if i login using the java version and navigate to the javascript version it is fine.  i have checked the cookies and they seem near identical.  it is strange.

**Comment by nlien** [comment]
I haven't used the java plugin, so I am unfamiliar with how that works. It could be worth to submit an issue to the team here: [https://issues.jboss.org/browse/KEYCLOAK
](https://issues.jboss.org/browse/KEYCLOAK)

I'll leave this issue open for a while, in case we'll have the time to study this.

(I'll agree it's strange.)

**Comment by chongma** [comment]
i upgraded keycloak 4.5.0 to 7.0.0 and this is now fixed
