### ISSUE TITLE
Update latest keycloak version

### ISSUE THREAD

**Issue by shaun12345678** [dsb-norge/vue-keycloak-js#37]
It would be nice if you can update to the latest keycloak version

**Comment by nlien** [comment]
Agreed. Hopefully we can spend some time testing the latest KC version in about a month or so. I suspect we don't have time this side of the year...

**Comment by anderius** [comment]
@shaun12345678: We are using Redhat SSO (the commercial offering) internally, and is therefore some versions behind.

Would it be useful if there was an option to point to the keycloak.js located on the keycloak server? It is described here:

https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter

```
The library can be retrieved directly from the Keycloak server at /auth/js/keycloak.js and
is also distributed as a ZIP archive.

A best practice is to load the JavaScript adapter directly from Keycloak Server as it will
automatically be updated when you upgrade the server. If you copy the adapter to your
web application instead, make sure you upgrade the adapter only after you have
upgraded the server.
```

**Comment by Brouilles** [comment]
Hi,
It's possible to know the version of Redhat SSO? Because I have problems with the last version of Keycloak. 

Thanks!

**Comment by baltom** [comment]
I'll close this one. Currently it's on keycloak version 9.0.3 because of redhat-sso also being there. 

A potensial solution to always be "up to date" is #59 without it we will most likely never be on the "latest and greatest" keycloak version
