### ISSUE TITLE
Adding idpHint to the configuration?

### ISSUE THREAD

**Issue by b0rski** [dsb-norge/vue-keycloak-js#40]
Is it somehow possible to add [idpHint](https://www.keycloak.org/docs/4.8/server_admin/#_client_suggested_idp) to the configuration of Keycloak?

I tried to use `config` and `init` but it seems that this option is only available in the `login` method of keycloak.

```
Vue.use(VueKeyCloak, {
    init: {
        onLoad: 'login-check',
        idpHint: 'azure,' // NOT WORKING
        checkLoginIframe: false
    },
    config: {
        realm: 'mypublicrealm',
        url: 'https://mypublicrealm.com/auth',
        clientId: 'fa7e101c'
    },
    onReady: () => {
        new Vue({
            router,
            store,
            components: LocalComponents,
            el: '#app',
            render: h => h(GlobalComponents.App)
        })
  }
});
```

**Comment by nlien** [comment]
Did you find a solution for this, since you closed this issue?

**Comment by b0rski** [comment]
No. I decided to use Keycloak JS adapter directly without the Vue plug-in.
