### ISSUE TITLE
I wrote a demo application

### ISSUE THREAD

**Issue by mimiz** [dsb-norge/vue-keycloak-js#41]
Hi guys, 

  Thanks a lot for the plugin, it helps me a lot !!
  I wrote and shared a "full demo" of integration, you can find it here https://github.com/mimiz/vue-auth-test Feel free to make me any comments ...

  Regards and thank you !

Rémi

**Comment by chongma** [comment]
if it is supposed to demonstrate best practices it would be good if 
url: "http://localhost:8080/auth",
clientId: "vue1",
realm: "demo-vue"
were stored in environment variables so they can be ignored by .gitignore

**Comment by nlien** [comment]
Thank you! Pleased to hear.

P.S. I'm closing this issue, since it's not really an issue...
