### ISSUE TITLE
How to skip some routes?

### ISSUE THREAD

**Issue by sppsun** [dsb-norge/vue-keycloak-js#43]
Hi, everyone

How to skip some routes, I mean I just need keycloak auth in specific routes?

Thanks.

**Comment by chongma** [comment]
if you are using vue-router you could add meta data to your routes use router.beforeEach to check whether the route has access?

**Comment by sppsun** [comment]
Hi,

Thanks for your reply.
Yes, I am using vue-router. In my project I want to create a login button, only user click the login button to redirect to keycloak and get a token.
But I can not know how to write the code in router.beforeEach to let vue-keycloak-js knows skip the routes. Sorry for my poor understanding.

Thanks.

**Comment by nlien** [comment]
Take a look at the example here:
https://github.com/dsb-norge/vue-keycloak-js/issues/2

**Comment by nlien** [comment]
There's also an example in the example folder.

**Comment by sppsun** [comment]
Thank you very much!
