### ISSUE TITLE
How to Logout?

### ISSUE THREAD

**Issue by h3nr1ke** [dsb-norge/vue-keycloak-js#44]
hello, 

how can I execute the logout from the current user?

also, how can I force reauthentication?

thank

**Comment by h3nr1ke** [comment]
For future needs

the injected `$keycloak` has a logout function

just call it 

```
$keycloak.logout()
```

and the user will be redirected to the login page once again

**Comment by chongma** [comment]
that is strange because i get `_vm.$keycloak.logout is not a function`.  i was using a redirect.  i am at version 1.1.2

**Comment by h3nr1ke** [comment]
you are right @chongma , the correct place is 

```javascript
Vue.use(VueKeyCloak, {
  onReady: (keycloak) => {
   // here we have the logout 
   keycloak.logout()
  }
})
```

I thought that was the same object of `$keycloak`

so, I added this object to my vuex store and inside my app call the logout function

hope it help you =)

**Comment by h3nr1ke** [comment]
Also,

following the [example](https://github.com/dsb-norge/vue-keycloak-js/tree/master/examples/hello-keycloak)

`$keycloak.logoutFn`

this is the way to call logout from the injected variable

=)

**Comment by TingNLP** [comment]
**Everyone who use keycloak logout should be notice this** 
https://stackoverflow.com/questions/71984843/keycloak-using-react-user-can-login-but-when-i-try-logout-i-get-a-message-inva
