### ISSUE TITLE
hello-keycloak example does not run on Mircrosoft Edge

### ISSUE THREAD

**Issue by h3nr1ke** [dsb-norge/vue-keycloak-js#45]
Hello,

If you just run the `hello-keycloak` example, you will realize that is does not work on Microsoft Edge, It makes the redirect to the keycloak server to authentication but when it returns, nothing happens.

I think that there is something with the Promise support... 

How to setup babel to proper work with vue-keycloak?

thanks for all the help

**Comment by nlien** [comment]
What version of Edge are you using? The "old" or the new, Chromium based?

**Comment by h3nr1ke** [comment]
Hello @nlien, thanks for the reply

the version is 

Microsoft Edge 41.16299.1004.0
Microsoft EdgeHTML 16.16299

this is the old one, right? (based in the application icon)

since we are using it inside our company computers, not sure if we can update right now =(

do you think that is possible to get it working using the old edge version?

thanks a lot

**Comment by h3nr1ke** [comment]
Just to confirm, that in the new version of EDGE

Version 83.0.478.45

the modules are working great =)

old edge still a problem... =(

**Comment by nlien** [comment]
Unfortunately, I am not in the position to test, reproduce and possibly fix this issue (I switched work). I'm not so sure this is about Promise support... AFAIK, Edge supports native Promises. IE however, not so much.

You can try to disable the checkLoginIframe. Something of a blindshot, but it has helped me before...Set the option `checkLoginIframe: false` in the options passed to the init method:
https://www.keycloak.org/docs/latest/securing_apps/index.html#session-status-iframe

**Comment by h3nr1ke** [comment]
@nlien thanks a lot for your time and dedication on this project

Now that we have a work around, just update edge browser, I think we can handle it.

its good to keep in record for future web searches =)

once again, thanks a lot...
