### ISSUE TITLE
Infinite refresh attempts with expired refresh token

### ISSUE THREAD

**Issue by anderius** [dsb-norge/vue-keycloak-js#5]
If the plugin is without internet access for a while (laptop in hibernation etc), the refresh token expires.
After this, it still tries to refresh, which will never success.

A possible fix can be to expose the `keycloak` object, and let the users handle all callbacks, including `onAuthRefreshError`.

**Comment by nlien** [comment]
Version 1.0.7 should fix this, and redirect tthe user to the login page, at least for cases where 'login-required' are used.
Ref: 5763d9d625a966a22fb1ee206578b69e614d9b13
