### ISSUE TITLE
I get unauthorized after ~10 mins

### ISSUE THREAD

**Issue by thisisme** [dsb-norge/vue-keycloak-js#51]
"@dsb-norge/vue-keycloak-js": "^1.1.3",

Vue.use(VueKeyCloakJs, {
  init: {
    onLoad: 'login-required'
  },
  config: {
    url: process.env.VUE_APP_SSO_URL,
    realm: process.env.VUE_APP_SSO_REALM,
    clientId: process.env.VUE_APP_SSO_CLIENTID
  },
  ...
})

In the console I have:
Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://url’) does not match the recipient window’s origin (‘null’).

What am I missing?

**Comment by thisisme** [comment]
After some more testing I can see that X-Frame-Options is set to SAMEORIGIN. I guess this is something that needs to be changed on the server where Keycloak is located?

**Comment by nlien** [comment]
Yes, that's something that needs to be addressed at the server level, IIRC.
https://www.keycloak.org/docs/latest/server_admin/#clickjacking

**Comment by anderius** [comment]
I am closing this, as the problem seems to be on the Keycloak configuration.
