### ISSUE TITLE
The Fuction hasRealmRole has some problem

### ISSUE THREAD

**Issue by GoodNight-Git** [dsb-norge/vue-keycloak-js#53]
Hello, I found some problems with the function 'hasRealmRole'.
I confirm if the account is admin by the function.
`this.$keycloak.hasRealmRole('C_ADMIN')`
But I found it get true then get false sometimes.
I don't know what happened.
So finally I use `this.$keycloak.realmAccess.roles.includes('C_ADMIN')`

**Comment by nlien** [comment]
Kinda hard to know without more information... This plugin just exposes the adapter's function. The hasRealmRole function in the adapter does almost exactly what your workaround is doing.

**Comment by anderius** [comment]
I am closing this, please reopen if there is something we can improve in the way we use keycloak.js.
