### ISSUE TITLE
pkce --need help!

### ISSUE THREAD

**Issue by wanglj-belink** [dsb-norge/vue-keycloak-js#54]
how can I use pkceMethod as on the keycloak.js?

**Comment by nlien** [comment]
You pass it to the init option:
```
Vue.use(VueKeyCloak, {
  init: {
    pkceMethod: 'S256'
  },
  onReady: kc => {
    new Vue({
      render: h => h(App)
    }).$mount('#app')
  }
})
```

**Comment by wanglj-belink** [comment]
> You pass it to the init option:
> 
> ```
> Vue.use(VueKeyCloak, {
>   init: {
>     pkceMethod: 'S256'
>   },
>   onReady: kc => {
>     new Vue({
>       render: h => h(App)
>     }).$mount('#app')
>   }
> })
> ```

It's not work

I think it may be that there is no exposed interface in the plug-in

![image](https://user-images.githubusercontent.com/63275142/92187736-2cf0cf00-ee8d-11ea-8a70-16dd74c1f071.png)
![image](https://user-images.githubusercontent.com/63275142/92187838-717c6a80-ee8d-11ea-99f3-bcb338c259ec.png)

**Comment by nlien** [comment]
Hopefully, the pull request (#52) awaiting merge, will have a new enough version where this option is available. Wait for it...

**Comment by christophernruud** [comment]
Have bumped KC to 9.x, please verify if this is adequate for your needs. Will try to look at an option to specify "latest" in future releases ref #37
