### ISSUE TITLE
Infinite refresh every 5 sec

### ISSUE THREAD

**Issue by UncleVic** [dsb-norge/vue-keycloak-js#55]
I have a problem.
In different browsers I can see page refresh every 5 sec. 
In some time keycloak.authenticated states is false.
App is redirecting to login page where understanding that token is valid. 
I think that depends of browsers setting or plugins because I don't have it before update Safari to new version.
However, my colleague has that problem from starting project

`import Vue from 'vue';
import App from './App.vue';
import store from './store';
import router from './router';
import VueKeyCloak from '@dsb-norge/vue-keycloak-js';
import { initAxios, vuetify } from './plugins';
import i18n from './i18n';

Vue.config.productionTip = false;

let keycloak = null;

Vue.use(VueKeyCloak, {
  config: {
    url: process.env.VUE_APP_KEYCLOAK_URL,
    realm: process.env.VUE_APP_KEYCLOAK_REALM,
    clientId: process.env.VUE_APP_KEYCLOAK_CLIENT_ID,
  },
  init: {
    onLoad: 'login-required',
  },
  onReady: kc => {
    keycloak = window.keycloak = kc;
    initKeycloak()
      .then(() => initAxios(kc.token))
      .then(initApp)
      .catch(authenticate);
  },
});

function initApp() {
  new Vue({
    store,
    router,
    vuetify,
    i18n,
    render: h => h(App),
  }).$mount('#app');
}

function initKeycloak() {
  return new Promise((resolve, reject) => {
    if (!keycloak.authenticated) reject(Error('401'));
    else {
      protectRoutes();
      resolve();
    }
  });
}

function protectRoutes() {
  router.beforeEach((to, from, next) => {
    keycloak.authenticated ? next() : authenticate();
  });
}

function authenticate() {
  if (keycloak.authenticated) return;
  window.location.replace(keycloak.createLoginUrl());
}
`

**Comment by UncleVic** [comment]
I solved it
Refresh there is when Third-Party Cookie were blocked.

**Comment by lewis-ing** [comment]
Hi @UncleVic Can you tell me how to fixed it? I met it,So I use js-cookie for my project, Now I don't how to fix it,do you detail how to fixed,thanks.

**Comment by UncleVic** [comment]
I don't think that it's right solution.
You need turn on Use Third-Party Cookie in setting yours browser.
I don't know why does't work LocalStorage in vue-keycloak-js. There is Code for it.
I can't see error, because code for create Storage is
``` js
function createCallbackStorage() {
    try {
      return new LocalStorage();
      } catch (err) {
    }
    return new CookieStorage();
}
```

I think, there is some error.

**Comment by UncleVic** [comment]
@anderius Can you check why doesn't create LocalStorage?
May be should show some message in console in that case?

**Comment by nlien** [comment]
> I don't think that it's right solution.
> You need turn on Use Third-Party Cookie in setting yours browser.
> I don't know why does't work LocalStorage in vue-keycloak-js. There is Code for it.
> I can't see error, because code for create Storage is
> 
> ```js
> function createCallbackStorage() {
>     try {
>       return new LocalStorage();
>       } catch (err) {
>     }
>     return new CookieStorage();
> }
> ```
> 
> I think, there is some error.

Just a clarification: your code example stems from the actual keycloak-js adapter, not this plugin

**Comment by lewis-ing** [comment]
Thx,@UncleVic And nlien,I figure out it，I check the vue-keycloak-js of doc and then view keycloak-js of doc,keycloak-js default 5s to refresh,So I setting checkLoginIframe:false for the configuration of man.js, To disable check login iframe, i still think to setting checkLoginIframe:true then it's check you sso for you all system on you browse.
![image](https://user-images.githubusercontent.com/5885520/96391890-e7922200-11ec-11eb-8939-91dbe321270f.png)
