### ISSUE TITLE
Vue 3.0 support

### ISSUE THREAD

**Issue by erwinmeesters** [dsb-norge/vue-keycloak-js#56]
Because Vue 3.0 is here......

**Comment by makurtu** [comment]
@nlien Is there any plans on porting this lib to Vue3? I really need it.

**Comment by nlien** [comment]
I am no longer the maintainer of this library, so I wouldn't know, I am afraid. Maybe others still in the organisation have any plans?

**Comment by makurtu** [comment]
Someone else? @anderius ?

**Comment by anderius** [comment]
We are waiting for Vuetify to support Vue 3 internally, therefore we did not use Vue 3 on our latest project. Maybe @baltom could elaborate?

**Comment by makurtu** [comment]
Many thanks @anderius ! If I can help on porting this lib to Vue 3 I could.

**Comment by baltom** [comment]
As @anderius says we dont have any Vue3 projects internally yet so this plugin has not yet been updated. But you are welcome to try it out @makurtu

**Comment by makurtu** [comment]
Yes! But I have to read more about Vue3 breaking changes. This lib is using some deprecated functions of Vue2.

**Comment by shlroland** [comment]
hi,I've submitted a PR to spport Vue3 #68 .Could you handle this PR as soon as possible？ @anderius

**Comment by anderius** [comment]
@shlroland Thank you for your contribution! We will look at it first thing after the holiday.

**Comment by baltom** [comment]
Vue 3 support added with 2.0.0-beta release. Although not 100% perfect yet it seems. Ref https://github.com/dsb-norge/vue-keycloak-js/releases/tag/v2.0.0-beta
