### ISSUE TITLE
Trigger updateToken

### ISSUE THREAD

**Issue by CryptoZorro** [dsb-norge/vue-keycloak-js#57]
Thanks for this helpful plugin.

I understand that there is an implicit token refresh, but I would like to trigger `updateToken()` before making an API call (or) as a part of error handling of an 403 response, like how it's mentioned in the JS adapter docs. How do I do this? 

I did try $keycloak.updateToken but this function is not exposed with the $keycloak instance. Is there any other way? Thanks in advance! 

```
keycloak.updateToken(60).then(function() {
    makeAPICall();
}).catch(function() {
    alert('Failed to refresh token');
});
```

**Comment by nlien** [comment]
I'm not sure if this will help you, but what about intercepting http requests and inspecting the status code?
For example with Axios, like this:
```javascript
axios.interceptors.response.use(response => {
  return response
}, error => {
  if (error.response.status === 403) {
    // Do something
  } else {
    return Promise.reject(error)
  }
})
```

**Comment by CryptoZorro** [comment]
Yes that's exactly what I wanted to do as well, my actual question was, where you got `// Do something`, how do call updateToken() and retry my api call?

**Comment by nlien** [comment]
If updateToken() from the Keycloak JS adapter is the only thing that'll help, I guess this function also has to be exposed.

I'm wondering if it's better to just expose the whole Keycloak object altogether, acting like a proxy, so every function/property is exposed always....

**Comment by CryptoZorro** [comment]
I agree, there could be many use cases, where I see the updateToken being manually triggered. For example, I would like to updateToken on window.onfocus()... The plugin will be flexible too!

**Comment by baltom** [comment]
@CryptoZorro  this should now be possible with version 1.3.1+ by doing Vue.$keycloak.keycloak.updateToken(60)
