### ISSUE TITLE
How to override login redirect_uri

### ISSUE THREAD

**Issue by alfreema** [dsb-norge/vue-keycloak-js#6]
I am using router.beforeEach to determine which routes require auth.   Works fine.

However, after logging out, it's desirable to allow a person to navigate to a route that requires authentication.  When they click a route requiring auth, I can get it to correctly call the login function, but I can't seem to control the redirect_uri.  It seems to always just use the route you are on (in this case /logout), instead of the route you are trying to go to.   Passing in a string to loginFn doesn't seem to do anything.   Is there a way to override the redirect_uri when calling loginFn?

**Comment by alfreema** [comment]
Ah, it actually works.  I needed to pass it like:    loginFn({ redirectUri: redirectUri }), instead of a simple parameter to the loginFn function.

**Comment by wolfuser99** [comment]
This should be in the Readme or in the Demo with the other options like:
```typescript
      const loginUrl = router.app.$keycloak.createLoginUrl({redirectUri:'http://localhost:8080/secret' })
      window.location.replace(loginUrl)
```
