### ISSUE TITLE
Could not initialized keycloak-js adapter at eval (dsb-vue-keycloak.umd.js:2556)

### ISSUE THREAD

**Issue by betterRunner** [dsb-norge/vue-keycloak-js#60]
Hi there, recently I have upload vue from 2.2.2 to 2.6.11, and it rasied an error when running init function, 
![image](https://user-images.githubusercontent.com/7123136/98076499-550aa780-1ea9-11eb-9c7e-9bdb74e398f5.png)
Any solution? Thanks in advanced!

**Comment by baltom** [comment]
@betterRunner The CORS error you had before the init function is that your keycloak instance? in that case i think you have configured your "Web Origins" incorrectly. That would usually give you a 403 when attempting to inject/run the iframe for keycloak, which again would make the init function not work

**Comment by betterRunner** [comment]
@baltom  Thanks for the reply. I think the CORS error occurs after the init function as it shows after the init function error. And I have also checked the request header of `https://172.16.90.121:9453/auth/realms/baas/protocol/openid-connect/token`, the autorization attribute is empty while the one in Vue 2.2 is like `authorization: Basic Y2xpZW50OjBiMDZkYTAwLTRhNWYtNGYwNi1iOTQ1LWNkMTFmMDg0YmEwMQ==`.

**Comment by baltom** [comment]
![Screenshot 2020-11-06 at 07 08 54](https://user-images.githubusercontent.com/10920353/98332629-52ba6180-1fff-11eb-9a69-0105796389e4.png)

Just tried to remove configuration of "Web Origins" in a keycloak instance. Doing so will cause the exact same error as you are seeing. So i feel pretty confident that it's the error you are now seeing.

Either you'll need to add the url: "http://172.16.90.129:8903" to your "Web Origins". Or you could add "+" to re-use all the URLs you've set as "Valid Redirect URIs". Or the less preferred setting "*" to allow everything

**Comment by betterRunner** [comment]
@baltom The above configurations work, thank you!

**Comment by andjimrio** [comment]
BTW, in my case, my keycloak's client wasn't public, but confidential. For this reason there is no client secret in the code, according to https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter
