### ISSUE TITLE
Specify that 127.0.0.1 not same as localhost

### ISSUE THREAD

**Issue by luisliz** [dsb-norge/vue-keycloak-js#63]
I know this is not a big issue but just in case anyone spends 2 hours trying to debug the plugin `127.0.0.1` cookies are not the same as `http://localhost` cookies. 

I would login with localhost and it would load initially but when I refreshed it would appear as not authenticated which is what caused the most confusion.

**Comment by baltom** [comment]
Added clearifying text: https://github.com/dsb-norge/vue-keycloak-js/blob/master/README.md#localhost--127001

It's not really an issue specific to this plugin as you say though. But maybe it will help people in the future ;) that is if they actually read the `readme.md` file hehe.
