### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by alfreema** [dsb-norge/vue-keycloak-js#7]
How can I call the underlying keycloak adapter's hasRealmRole( ) function?   I am missing how to check roles with this plugin.

**Comment by nlien** [comment]
In the onReady callback, you have access to the keycloak object. You could maybe get the roles by accessing `keycloak.tokenParsed['authorities'] `? Or just call the hasRealmRole function directly?

**Comment by alfreema** [comment]
Okay, is there a way to access the underlying keycloak object using this.$keycloak?

**Comment by nlien** [comment]
Not yet, I'm afraid. There are certain callback functions, like onAuth*, on the keycloak object, which we'd rather not expose. Because overriding them would break the plugin's behavior. Maybe we'll expose more of the underlying object in the near future... In the meantime go for my suggestion above, or use the token from `this.$keycloak.token` and parse it yourself.

**Comment by alfreema** [comment]
I don't think I can use onReady, because no authentication has taken place at that point.   I'll look into parsing this.$keycloak.token though.

**Comment by nlien** [comment]
Hi again... `keycloak.tokenParsed['authorities']` may not be what you want, I realize. Behind the scenes, Keycloak's `hasRealmRole` function inspects the `keycloak.realmAccess.roles` array for the given role. If you'd still like to have the `hasReamRole()` exposed on the `$keycloak` object, I'll ship a new version with this added. Just let me know by replying here.

**Comment by anderius** [comment]
I vote for exposing both `hasRealmRole` and `hasResourceRole`.

**Comment by alfreema** [comment]
Sorry for delayed responses, I am not in front of a computer as much as I'd like to be these days.  :)   I'll leave that up to you gurus, I just need a somewhat future-proof way to authorize using roles.   Implementing a function that maps to hasRealmRole seems to be the easiest in my pea-sized brain.

**Comment by nlien** [comment]
Exposed hasRealmRole and hasResourceRole in v1.0.9
