### ISSUE TITLE
Multi Tenancy / Change configured realm

### ISSUE THREAD

**Issue by ma-sch** [dsb-norge/vue-keycloak-js#74]
I'm developing a Vue.js (Version 2) application  that needs to support multi-tenancy. Each tenant is represented by a Keycloak realm. Before the actual login, the user shall select the relevant realm. Therefore I created a pre-login page with a simple dropdown for realm selection. After the selection, the login process should be started and the login page of the corresponding realm should be opened.

Because the Vue instance needs to be created to display the pre-login page for realm selection, my idea was to move the Vue.use(VueKeyCloak) part from main.js into my pre-login page component and to call it after the user selected a realm. But that didn't work. I think it's because Vue.use() has to be called before calling new Vue() (as described in [Vue.js documentation](https://vuejs.org/v2/guide/plugins.html)). 

So my question is: How to change the configured realm of the plugin/keycloak adapter after the plugin has been initialized and the Vue instance has been created? If this is not possible, I would be grateful for hints on how to implement the functionality in a different way.

**Comment by baltom** [comment]
Your idea should be possible. You do not need to call Vue.use before vue itself is created. So you should be able to create vue normally in main.js. And have your initial "select realm view" component. Then with a click of a button in this component you could trigger loading of vue-keycloak

As for your question, it's not possible to modify the realm after you have loaded the plugin. As it has an "install guard" so the underlying keycloak-js adapter is only initialized once

**Comment by lukaslaskovski** [comment]
The problem arises when the user logs out and decides to log in to another organization with different `realm`.

Maybe some method forcing the reinitialization of `new Keycloak`?
