### ISSUE TITLE
使用vue3 集成keycloak出现问题

### ISSUE THREAD

**Issue by cyccess** [dsb-norge/vue-keycloak-js#77]
哈喽！

我在使用vue3集成keycloak时，导入模块出现以下问题，另外在npm包dist目录中我没有发现 types.d.ts文件。

import VueKeycloakJs from '@dsb-norge/vue-keycloak-js'
 
无法找到模块“@dsb-norge/vue-keycloak-js”的声明文件。“c:/Users/CHENG/xndb-client-work/node_modules/@dsb-norge/vue-keycloak-js/dist/dsb-vue-keycloak.cjs.js”隐式拥有 "any" 类型。
  尝试使用 `npm i --save-dev @types/dsb-norge__vue-keycloak-js` (如果存在)，或者添加一个包含 `declare module '@dsb-norge/vue-keycloak-js';` 的新声明(.d.ts)文件ts(7016)

`import { createApp } from "vue";
import VueKeycloakJs from '@dsb-norge/vue-keycloak-js'
import App from "./App.vue";
import router from "./router";
import store from "./store";

import {KeycloakInstance} from "keycloak-js";
import {VueKeycloakInstance} from "@dsb-norge/vue-keycloak-js/dist/types";

createApp(App).use(VueKeycloakJs,{
  init: {
    // Use 'login-required' to always require authentication
    // If using 'login-required', there is no need for the router guards in router.js
    onLoad: 'check-sso',
  },
  config: {
    url: process.env.VUE_APP_CLIENT_URL,
    realm: 'xndb',
    clientId: process.env.VUE_APP_CLIENT_ID
  },
  onReady (keycloak: KeycloakInstance) {
    console.log('Keycloak ready', keycloak)
  }
}).use(store).use(router).mount("#app");

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties  {
    $keycloak: VueKeycloakInstance
  }
}`

**Comment by baltom** [comment]
We don't speak chinese. However if we are to trust that google translate is good enough you are trying to use the plugin with vue 3? You need to use version 2.0.0-beta for the vue 3 support, as well as the typescript typings.

**Comment by LarryEitel** [comment]
Here is the error in English:

`Issues checking in progress...
ERROR in src/main.ts:2:27
TS7016: Could not find a declaration file for module '@dsb-norge/vue-keycloak-js'. 'C:/__repos/deel/sfm/_wip/vue-keycloak-js/examples/typescript_vue3/node_modules/@dsb-norge/vue-keycloak-js/dist/dsb-vue-keycloak.cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/dsb-norge__vue-keycloak-js` if it exists or add a new declaration (.d.ts) file containing `declare module '@dsb-norge/vue-keycloak-js';`
    1 | import { createApp } from 'vue'
  > 2 | import VueKeycloakJs from '@dsb-norge/vue-keycloak-js'
      |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    3 | import App from './App.vue'
    4 | import {KeycloakInstance} from "keycloak-js";
    5 | import {VueKeycloakInstance} from "@dsb-norge/vue-keycloak-js/dist/types";

ERROR in src/main.ts:5:35
TS2307: Cannot find module '@dsb-norge/vue-keycloak-js/dist/types' or its corresponding type declarations.
    3 | import App from './App.vue'
    4 | import {KeycloakInstance} from "keycloak-js";
  > 5 | import {VueKeycloakInstance} from "@dsb-norge/vue-keycloak-js/dist/types";
      |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    6 |
    7 | createApp(App)
    8 |   .use(VueKeycloakJs, {
`

**Comment by cyccess** [comment]
> We don't speak chinese. However if we are to trust that google translate is good enough you are trying to use the plugin with vue 3? You need to use version 2.0.0-beta for the vue 3 support, as well as the typescript typings.

thanks a lot! I added the typings attribute myself to the package.json file.
