### ISSUE TITLE
Documentation on keycloak callback events

### ISSUE THREAD

**Issue by stijnwesterhof** [dsb-norge/vue-keycloak-js#87]
I'm trying to make use of the `onAuthSuccess` callback event. I've seen this on the keycloak documentation: `keycloak.onAuthSuccess = function() { alert('authenticated'); }`, but how would a do that with this implementation of keycloak? If tried: `Vue.prototype.$keycloak.onAuthSuccess = function() { alert('authenticated'); }`, but that doesn't seem to work.

Can you please update the read.me?

**Comment by baltom** [comment]
The object you get from `$keycloak` is not the original keycloak instance itself. If you would like to access that you can reach it at `$keycloak.keycloak` where you could also access `onAuthSuccess`. However i do think that if you override that function the auto-renewal functionality in this plugin will stop working for you. So you would most likely have to implement said functionality in what you are attempting to achieve

**Comment by stijnwesterhof** [comment]
Thank you @baltom ! You can close this issue if you want.

I have another question that could maybe help me with. Is it possible to manually set the access_token & refresh_token? We have a create account endpoint and in the response, I receive the new user info and the tokens. I would like to be able to have this new user be signed in after sign up. Is there a method to log in the new user with this received token? `Vue.$keycloak.token = token` doesn't seem to do the job

**Comment by baltom** [comment]
Not quite sure about that one. Following the regular process of registrering a user through keycloak should send the user through the "correct ways" with the correct tokens. I don't think it's a good idea to attempt to override these values. 

If by creating an account through your endpoint also creates a valid session in keycloak for said user you should be able to force update the user's tokens with the `$keycloak.keycloak.updateToken` method though

**Comment by stijnwesterhof** [comment]
Is there any way to initialize keycloak with access and refresh token received from our own API? We've built our own login and registration pages/endpoints, but I would still like to use the keycloak javascript adapter to use the updateToken method for example.

**Comment by stijnwesterhof** [comment]
> Or created your own custom endpoints (backend) for keycloak which you trigger keycloak functionality from and want to use tokens coming from said custom endpoint in this plugin?

Exactly this. I didn't build this myself though. I can send the credentials to an endpoint (login & registration), and then I receive an acces_token and a refresh_token. These tokens are coming from keycloak.

**Comment by baltom** [comment]
But you do get a valid keycloak session from using said endpoint? So if you register and account through it and then refresh you frontend application thereby forcing the user to go to the keycloak login screen. If you have `login-required` configured. Or forcing the `silent-check-sso` functionality to run. He/She would be send back with a valid access token/refresh token like in the regular "keycloak way" ? 

Or have you through this endpoint only created an account, and given a valid access token and refresh token back without actually creating a session for the user?

**Comment by baltom** [comment]
If it's the first one you should be able to just force update the token by doing a `$keycloak.keycloak.updateToken(300)`

If it's the latter, maybe you can override the tokens by doing `$keycloak.keycloak.token = newToken` and `$keycloak.keycloak.refreshToken = newRefreshToken`. But uncertain if that works 🤔  Or you would have to create your own "refresh functionality" by duplicating the functionality of keycloak-js adapter and this plugin

**Comment by stijnwesterhof** [comment]
Manually setting the token doesn't seem to work, unfortunately. I think it's weird that there's no real solution to my problem. I can't imagine that there's no other project with keycloak where they want to keep the login and registration on their own website. I've seen some examples with Auth0 tho and that seems to use the same JWT technology.

Thanks for the help anyway!
