### ISSUE TITLE
Newbie question...component rendered before auth kicks in

### ISSUE THREAD

**Issue by aminmc** [dsb-norge/vue-keycloak-js#88]
Hi there, 

I'm new to Vue and I'm trying to plug this module in. I'm using the following code:
```
createApp(App)
    .use(VueKeycloakJs, {
        init: {
            onLoad: 'login-required',
        },
        config: {
            url: 'http://localhost:8080/auth',
            clientId: 'xxx',
            realm: 'xxx'
        },
        onReady (keycloak) {
            console.log('Keycloak ready', keycloak)
            keycloak.updateToken(60).then(() => {
                console.log("Token refreshed")
            })
        }
    })
    .use(router)
    .use(logger)
    .mount('#app');
```
In one of my components I have this bit of code:

```
const app = getCurrentInstance()
const props = app.appContext.config.globalProperties.$keycloak
log.info(`Hello`, props);
```

What I'm noticing is that log statement outputs before the auth kicks in resulting in all the properties being empty.  It's worth mentioning I'm using vite as well so whenever I try 'Vue.propotype.$keycloak' I get a different error. 

I would expect the first middleware to kick in first and then subsequent ones.  I mean this could be a user error issue so any help would be appreciated.

Thanks

**Comment by baltom** [comment]
Many Vue plugins loads asynchronously. So it will continue the "chain" even though it is not yet finished. But still because the $keycloak object is initialized "immediately" you have access to it. What your log statement is probably the $keycloak object initialized here https://github.com/dsb-norge/vue-keycloak-js/blob/master/src/index.ts#L28 if you want to use the contents of the object one trick is to use the `onReady` callback in the plugin configuration. Or you would have to create some mechanism which waits until the keycloak object is "ready".

**Comment by aminmc** [comment]
Hi there,

I've changed the code to do this
```
const app = createApp(App);

    app.use(VueKeycloakJs, {
        initOptions: {
            onLoad: 'login-required'
        },
        config: {
            url: 'http://localhost:8080/auth',
            clientId: 'eforms',
            realm: 'elf'
        },
        onReady: (keycloak) => {
            app.use(router)
                .use(logger)
                .mount('#app');
            keycloak.updateToken(60).then(() => {
                console.log("Token refreshed")
            })
        }
    });
```
Does this seem reasonable to you?

**Comment by baltom** [comment]
It's probably the easiest solution to the problem. But it also slows down the initial "time to draw" of your application. As in it will stay white until your keycloak responds and the plugin loads fully. Which may be no problem for you though

**Comment by aminmc** [comment]
Ok. The other option is to get hold of the keycloak object in a layout template and present a loading bar if it's not initialised?

**Comment by baltom** [comment]
Yeah something like that. So you'll be able to show to the end user that your app has started but is still "doing something"
