### ISSUE TITLE
How to use keycloak object in router

### ISSUE THREAD

**Issue by aminmc** [dsb-norge/vue-keycloak-js#89]
Hi,

I have the following router configuration:
```
import { createRouter, createWebHistory } from 'vue-router'
import Dashboard from '@/components/Dashboard.vue'
const routes = [
    {
        path: '/',
        name: 'Dashboard',
        component: Dashboard,
    },
    {
        path: "/:catchAll(.*)",
        redirect: '/'
    }
]
const router = createRouter({
    history: createWebHistory(),
    routes,
});

router.beforeEach((to, from, next) => {    
    next();
});
export default router
```
What I'd like to do is in the beforeEach apply a couple of checks centred around the keycloak object but I'm not sure how to get hold of the keycloak object.  I've tried :

```
Vue.prototype.$keycloak
```
But as I'm using vite and Vue3  I get an exception. I've tried 

```
route.app.$keycloak

```
But no result for that one.  I've also tried:

```
getCurrentInstance().appContext.config.globalProperties.$keycloak
```

No result on that either. 

Is there a way to get hold of the keycloak object in the router configuration? 

Sorry for the second issue of the day. Just trying to sort the project structure out. 

Thank you.

**Comment by baltom** [comment]
My experience using Vue3 is rather low. So i am not quite sure myself. If you export your Vue app instance from your setup maybe you could import it here in the router and then access it's contents?

**Comment by ArnaudPigne** [comment]
As you’re using Vue3, you’re using vue-route 4.
And **router.app as been removed** : https://next.router.vuejs.org/guide/migration/index.html#removal-of-router-app.

But, you can "_extend the TypeScript definition of the Router interface to add the app property._" as the documentation said.
In your main.ts:
```
const app = createApp(App)
    .use(router)
    .mount('#app')
    
declare module 'vue-router' {
    interface Router {
        app: ComponentPublicInstance
    }
}

router.app = app
```

So in your router.ts you can safely use:
`router.app.$keycloak`

**Comment by baltom** [comment]
Closing this issue as i'd imagine that @ArnaudPigne's answer will do the trick
