### ISSUE TITLE
Let others callbacks available

### ISSUE THREAD

**Issue by LeandrodeLimaC** [dsb-norge/vue-keycloak-js#92]
Hello! i was trying out this package and i found it quite interesting
In my app i would like to execute some functions when specifics callbacks are called inside keycloak, like the following:

```
Vue.use(VueKeycloakJs, {
  onReady:() => {
    new Vue({
      router,
      store,
      vuetify,
      render: (h) => h(App)
    }).$mount('#app');
  },
  onAuthSuccess: () => {
    const user = {
      name: keycloak.idTokenParsed.given_name,
      email: keycloak.idTokenParsed.email,
      userId: keycloak.idTokenParsed.preferred_username,
      accessToken: keycloak.token,
    }

    store.dispatch("Auth/userLoggedIn", user);
  },
  onAuthRefreshSuccess: () => {
    store.dispatch('Auth/updateToken', keycloak.token)
  }
```

But i couldn't make it work, i'm new with keycloak so if there's something i'm doing wrong or missing i would love to know!
Thanks for the cool work!

**Comment by baltom** [comment]
Your callbacks in this case would be unnecessary. The $keycloak object exposed on the Vue prototype is reactive. Meaning any changes made to it would trigger updates "downwards". 

You could use the $keycloak object directly in all these cases. 

Display user information in a view:
```
<p>{{ $keycloak.idTokenParsed.given_name }} - {{ $keycloak.idTokenParsed.email }}
```
These would automatically update if the values changes for some reason. 


And if you need to use the access token for calling backend or something you could extract the token from `Vue.prototype.$keycloak.token` (vue2). Which again would automatically change every time the access token is updated

**Comment by LeandrodeLimaC** [comment]
Oh, I see! Thanks for the explanation! that's exactly what I need to do
