### ISSUE TITLE
Error: Could not initialized keycloak-js adapter - dsb-vue-keycloak.umd.js:125

### ISSUE THREAD

**Issue by Excel1** [dsb-norge/vue-keycloak-js#93]
By using the example 'typescript_vue3' i got an javascript console error and couldnt get logged-in:

```
https://my.keycloak.com/auth/realms/mrealm/protocol/openid-connect/login-status-iframe.html/init?client_id=myclient&origin=http://localhost:8080 - [HTTP/3 403 Forbidden 321ms]
```

right after this i got
```
Error: Could not initialized keycloak-js adapter - dsb-vue-keycloak.umd.js:125
```

The settings for the realm in keycloak-js are correct and also https://localhost:8080/* is allowed as redirect uri

By using 'hello-keycloak' i got the following error and get successfully redirect to my keycloak login page after clicking on secret. Then i will be redirected to the account settings page /account/applications.
```
Error: Could not initialized keycloak-js adapter
    init dsb-vue-keycloak.umd.js:2556
 undefined dsb-vue-keycloak.umd.js:2557
    init dsb-vue-keycloak.umd.js:2557
```

What iam doing wrong?

**Comment by Excel1** [comment]
Additional Information: 
I try to connect Quasar CLI with keycloak js like this: https://github.com/quasarframework/quasar/issues/9950#issuecomment-873623252

**Comment by baltom** [comment]
How does your "Web Origins" look like in keycloak?
![image](https://user-images.githubusercontent.com/10920353/124872049-12174b80-dfc5-11eb-8004-86a456226f62.png)

You would usually see this 403 error if it's not configured correctly. Either it needs to be '+' to re-use all your "Valid Redirect URIs". Or the less secure version "*" which will allow everything

**Comment by Excel1** [comment]
Using Vue3 Tpescript:
I use m private ip address 192.168.178.44:8080/* and i got less errrors.
GET https://my.kecloak.com/auth/realms/myrealm/protocol/openid-connect/login-status-iframe.html/init?client_id=mclientid&origin=http%3A%2F%2F192.168.178.44%3A8080
[HTTP/3 403 Forbidden 267ms]

Error: Could not initialized keycloak-js adapter - dsb-vue-keycloak.umd.js:125

Using hello_keycloak:
Error: Could not initialized keycloak-js adapter

And if i click on secret i can login but:

POST https://my.kecloak.com/auth/realms/myrealm/protocol/openid-connect/token
CORS Missing Allow Origin

Error: Could not initialized keycloak-js adapter - dsb-vue-keycloak.umd.js:2557

**Comment by baltom** [comment]
Did you look at your Web Origins configuration on your "mclientid" client in keycloak? 

In your previous post you were using localhost:8080, where my picture would configure correctly. And now you changed it to 192.168.178.44:8080. Which would make the above configuration incorrect. You either need to specify all URLs you are using in your Web Origins. Or use '+' or the less secure '*'. Like described in my previous answer

**Comment by Excel1** [comment]
![MyClient](https://user-images.githubusercontent.com/9309456/125034052-6e936d00-e090-11eb-9ff2-3515bdecf9c2.png)

This is how i set it up

**Comment by baltom** [comment]
Need to remove the ending /* in the Web Origins. As they are using your Origin header which does not contain the /* at the end

**Comment by Excel1** [comment]
Many many thanks!! It works now 👍🏻 

I thought i could wildcard there... Sorry for wasting your time.
