### ISSUE TITLE
Keycloak with Vue3 + Typescript shows no output after reload

### ISSUE THREAD

**Issue by DnD2k21** [dsb-norge/vue-keycloak-js#96]
Hi, 
can someone help me in this case?
I cloned and used that typescript project from example folder.
It is with vue 3.

I made adjustments regarding my localhost address which is 8080 Port.
and other changes like realm, clientid, url etc. as per my own keycloak configuration..

But it shows output only first time, if we reload the page it shows nothing.

I also checked it renders SECRET.vue , but not going in that if condition ( <div v-if="$keycloak && $keycloak.ready"> ).

My main.ts looks like this.

  ```
import { createApp } from 'vue'
  import VueKeycloakJs from '@dsb-norge/vue-keycloak-js'
  import App from './App.vue'
  import {KeycloakInstance} from "keycloak-js";
  import {VueKeycloakInstance} from "@dsb-norge/vue-keycloak-js/dist/types";


  createApp(App)
    .use(VueKeycloakJs, {
      init: {
       onLoad: 'login-required',
      },
    config: {
      url: 'https://auth-keycloak002.xxxxxxxx.de/auth/',
      clientId: 'xxxxxxx',
      realm: 'xxxxx'
    },
    onReady (keycloak: KeycloakInstance) {
      console.log('Keycloak ready', keycloak)
    }
  })
  .mount('#app')

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties  {
    $keycloak: VueKeycloakInstance
  }
}
```

Am i missing something?

**Comment by baltom** [comment]
Im guessing your are hitting the "Reason for '-beta'" https://github.com/dsb-norge/vue-keycloak-js/releases/tag/v2.0.0-beta not quite sure why the vue 3 version doesn't trigger the view to redraw when the object changes.

**Comment by gauti92** [comment]
> Im guessing your are hitting the "Reason for '-beta'" https://github.com/dsb-norge/vue-keycloak-js/releases/tag/v2.0.0-beta not quite sure why the vue 3 version doesn't trigger the view to redraw when the object changes.

But their own example from official Dokumentation should work i think.

**Comment by baltom** [comment]
Im afraid not. It's an error which i haven't been able to fix. Even for the examples. Its an issue for all vue 3 projects (using this plugin) as far as i'm aware. We (DSB-norge) are not yet using vue 3, so haven't really gotten the time to learn the ins and outs of vue 3. And instead of keeping non-released code commited we added the `-beta` tag release(s) so people can still use the other features which came with version 2.x.x.

**Comment by baltom** [comment]
Can you test this with the latest release 2.1.1-beta
