### ISSUE TITLE
Can't resolve imported dependency VueKeycloakInstance - Vue3, Quasar

### ISSUE THREAD

**Issue by FKonig** [dsb-norge/vue-keycloak-js#97]
Hi,
this might be a bit of a noob question but I am struggling accessing 'this.$keycloak'.
I tried following the readme and adapting it for a non TypeScript project. 
Everything worked so far (login, redirect). But I am struggling with retrieving the token in my components using 'this.$keycloak.token'.

The following is my VueKeycloak boot script (similar to main.js in non Quasar projects):

```
import { boot } from 'quasar/wrappers'
import VueKeyCloak from '@dsb-norge/vue-keycloak-js'
//import { VueKeycloakInstance } from "@dsb-norge/vue-keycloak-js/dist/types";



// "async" is optional;
// more info on params: https://v2.quasar.dev/quasar-cli/boot-files
export default boot( ( { app } ) => {

  function tokenInterceptor () {
    app.config.globalProperties.$api.interceptors.request.use(config => {
      config.headers.Authorization = `Bearer ${config.globalProperties.$keycloak.token}`
      return config
    }, error => {
      return Promise.reject(error)
    })
  }
  
  let initOptions = {
    config : { url: 'https://my.keycloak.com/auth', realm: 'myRealm', clientId: 'web-app' },
    init : { onLoad: 'login-required' },
    onReady: (keycloak) => { tokenInterceptor() }
  }

  app.use(VueKeyCloak, initOptions);  

  //app.config.globalProperties.$keycloak = VueKeycloakInstance;

})
```

If I uncomment line 3 I get the following error:

> Module not found: Can't resolve imported dependency "@dsb-norge/vue-keycloak-js/dist/types"
Did you forget to install it? You can run: npm install --save @dsb-norge/vue-keycloak-js/dist/types

In the last line (currently commented out) I want to add $keycloak as a global property but I cannot do this without importing the instance...

Any help is appreciated.

**Comment by baltom** [comment]
The two lines you have already commented out should not be needed. The plugin itself will add itself to the globalProperties object. https://github.com/dsb-norge/vue-keycloak-js/blob/master/src/index.ts#L95.

Yet with these commented out you still get an error? Or what happens in your component? Note however as mentioned in  the release notes for 2.x.x as well as https://github.com/dsb-norge/vue-keycloak-js/issues/96 that there is a bug with vue 3 when it comes to drawing updated contents of the $keycloak object. The object itself seems to update just fine. But it doesn't cause a redraw of the views.

**Comment by FKonig** [comment]
I see, sorry. The second Vue 3 example in the readme confused me.
Indeed, I can access this.$keycloak in my component leaving the two lines commented out. However I am trying to grab some data from an API in the mounted() hook but I always just get null when I try to access this.$keycloak.token. It seems like $keycloak isn't ready yet (this.$keycloak returns undefined)? Is there some callback function that I can use when it is ready?
As a crude fix I tried logging this.$keycloak to the console after a timeout but even that just logs 'undefined'. However, after a while I can see that this.$keycloak is holding the correct data...

My components mounted() function:
```
mounted() {
    console.log(this.$keycloak); // 1
    setTimeout(function(){console.log(this.$keycloak)}, 5000); // 2
    let token = this.$keycloak.token; // 3
    this.$api.get('/myapi', {headers: {'X-Authorization': 'Bearer ' + token },})
      .then(function (response) {
        // handle success
        console.log(response);
      })
  }
```
1 - logs $keycloak with all properties null, but after a while I can see in the console that it gets the correct property values
2 - logs 'undefined'
3 - returns null

**Comment by gauti92** [comment]
> I see, sorry. The second Vue 3 example in the readme confused me.
> Indeed, I can access this.$keycloak in my component leaving the two lines commented out. However I am trying to grab some data from an API in the mounted() hook but I always just get null when I try to access this.$keycloak.token. It seems like $keycloak isn't ready yet (this.$keycloak returns undefined)? Is there some callback function that I can use when it is ready?
> As a crude fix I tried logging this.$keycloak to the console after a timeout but even that just logs 'undefined'. However, after a while I can see that this.$keycloak is holding the correct data...
> 
> My components mounted() function:
> 
> ```
> mounted() {
>     console.log(this.$keycloak); // 1
>     setTimeout(function(){console.log(this.$keycloak)}, 5000); // 2
>     let token = this.$keycloak.token; // 3
>     this.$api.get('/myapi', {headers: {'X-Authorization': 'Bearer ' + token },})
>       .then(function (response) {
>         // handle success
>         console.log(response);
>       })
>   }
> ```
> 
> 1 - logs $keycloak with all properties null, but after a while I can see in the console that it gets the correct property values
> 2 - logs 'undefined'
> 3 - returns null

Yeah, 
as @baltom already mentioned i am also facing same issue here [https://github.com/dsb-norge/vue-keycloak-js/issues/96]
(url) . I am able to see the output just once on my console and it draws the output correctly but when i reload the Page it shows null whatever property u need from $keycloak or this.$keycloak... 
I even tried to save those values in a data and a prop, but nothing works..
But i think it's in beta which is why we should wait for the actual release with vue3.

But, i would also recommend @dsb-norge to modify their read me, because i also invested more than 2 days just for this beta version, i also got confused because of Vue 3 typescript example.

Or 

They should also include that in read me that it is in Beta version and Vue 3 is not fully supported yet.

**Comment by DnD2k21** [comment]
> @DnD2k21 I have hopefully made it better here: #108
> 
> Please add your comments if you see any improvement!

Thanks it looks better now!
Just waiting for full vue3 support release.
👍🏽
