### ISSUE TITLE
Old Version of Keycloak-JS potentially causes infinite reloading

### ISSUE THREAD

**Issue by BloodWorkXGaming** [dsb-norge/vue-keycloak-js#99]
I am facing the problem of infinit reloading about every 5 seconds.

As I found in this post, it could be caused by a difference in the version of keycloak vs keycloak-js:
https://stackoverflow.com/questions/55606931/keycloak-js-library-iframe-redirect-when-alreadylogged-in

This library seems to be using version 9 while the version 15 is already out.

Is it possible to update it? Or is the refresh loop caused by something else?

**Comment by rgrosjean** [comment]
Is it not possible to force the installation of the latest version of keycloak-js? Could be a try.
Could also be related to this https://github.com/dsb-norge/vue-keycloak-js/issues/1

**Comment by BloodWorkXGaming** [comment]
So after further testing:
- Updating to keycloak-js 15 didn't help (Used this package for forcing the version: https://www.npmjs.com/package/npm-force-resolutions)
- Setting VueRouter to history mode didn't fix the reloading bug
- Commenting out `Vue.use(VueRouter)` and the other router parts didn't fix the problem either

Would be glad if anyone has any ideas :)

**Comment by BloodWorkXGaming** [comment]
Okay, I found the cause for the issue:

As I was hosting both services on localhost, I always got a CORS error.
This caused an infinit reload loop in Firefox and just a white screen in chromium based browser.
After moving keycloak behind a reverseproxy on the /auth url it now works (only tested it with v15 of keycloak-js)

Would love to see better error handling for such edge cases :)

Leaving this open for the Maintainers to decide and close

**Comment by eidottermihi** [comment]
I can confirm @BloodWorkXGaming workaround is indeed working:
- forcing `keycloak-js` version to v15 with `npm-force-resolutons`
- using a Keycloak instance thats not running on localhost

**Comment by baltom** [comment]
As mentioned on previous issues we are currently sticking to version 9.0.3 because of redhat-sso being behind keycloak. And we are not using keycloak. 

In regards to better error handling, i've been trying to catch common errors. However most of them are not exposed by keycloak-js plugin. Like the CORS error is coming from the iframe which does not return errors to "us".

**Comment by eidottermihi** [comment]
@baltom latest Red Hat SSO v7.5 uses Keycloak 15 (see https://access.redhat.com/articles/2342881 ) - would you mind reconsidering the decision to not upgrade the keycloak-js adapter dependency ?

Maybe by releasing a new major version v3 (so Keycloak 9 users can stick to v2)? 

I'm happy to provide PRs if help is needed.
